In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [2]:
df = pd.read_csv('./data/PCA_Output.csv').drop('Unnamed: 0', axis=1)
df.head()

,PC-1,PC-2,PC-3,PC-4,PC-5,PC-6,PC-7,PC-8,PC-9,PC-10,...,PC-14,PC-15,PC-16,PC-17,PC-18,PC-19,PC-20,Year,Round,School
0,9.793161,-3.870768,0.568076,3.796580,1.705862,0.176409,-1.241633,-2.516725,-1.307687,-0.169022,...,-0.247870,0.437014,0.074986,-0.552336,-0.173708,-0.071517,0.020674,1,0,Duke
1,0.457927,2.158733,-3.331555,-1.732875,-0.905384,0.484283,0.393627,-1.085547,-2.091268,0.381519,...,0.794063,-0.733679,0.655320,-0.080461,-0.106335,-0.045669,-0.253534,4,0,Connecticut
2,4.999635,-0.703702,2.017771,0.126519,-0.345192,-1.071220,-0.469528,0.539328,-0.394875,-0.157588,...,-0.236776,0.153043,0.208064,-0.114682,0.647572,0.335118,-0.247451,10,0,Duke
3,2.303384,2.758823,-2.833362,-0.163718,-2.071307,0.135062,-0.233750,-0.449236,-0.426468,0.470057,...,0.069364,-0.776026,0.560743,-0.331465,0.392254,0.168885,-0.087240,0,0,Michigan State
4,6.984694,-1.371949,-0.479680,2.610713,-1.085366,0.496063,0.909389,2.021656,-1.229714,0.489195,...,0.096316,0.921526,-0.207069,-0.334988,0.940922,-0.408270,-0.223398,6,0,Florida

In [3]:
df_test = df.sample(frac=.2, replace=False, random_state=0).copy()
df_train = df.drop(df_test.index).copy()

features_train = df_train.drop(['Year', 'Round', 'School'], axis=1)
features_test = df_test.drop(['Year', 'Round', 'School'], axis=1)

features_train = (features_train - features_train.mean())/features_train.std()
features_test = (features_test - features_test.mean())/features_test.std()

targets_train = df_train.Round
targets_test = df_test.Round

In [5]:
grid = {'C': [.01, .1, 1, 10]}

svc = SVC()
svcCV = GridSearchCV(svc, param_grid=grid, return_train_score=True, n_jobs=-1)
svcCV.fit(features_train, targets_train)

print(svcCV.best_params_, svcCV.best_score_)

print(svcCV.score(features_test, targets_test))

pred = svcCV.predict(features_test)

print(np.mean(abs(pred - targets_test)))

{'C': 0.01} 0.16666666666666666
0.045454545454545456
2.0

In [6]:
pred

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      dtype=int64)